apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - kube-state-metrics-config.yaml
  - monitoring-config.yaml


