apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-config
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
  path: "./monitoring/configs"
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kube-prometheus-stack
      namespace: monitoring
  timeout: 1m
  wait: true