apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/kube-prometheus-stack
  - ../base/hello-app
patches:
  - path: kube-prometheus-stack-values.yaml
    target:
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: monitoring
  - path: hello-app-values.yaml
    target:
      kind: HelmRelease
      name: hello-app
      namespace: app
#---
#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization
#namespace: app
#resources:
#  - ../base/hello-app
#patches:
#  - path: hello-app-values.yaml
#    target:
#      kind: HelmRelease