apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hello-app-helm-repo
  namespace: app
spec:
  interval: 10m
  url: https://github.com/lamtruong1609/hello-app
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
